INSERT INTO autores (nombre_completo) VALUES
('Cárdenas, T. H.'),
('Emmer, M.'),
('Lax, P.'),
('Mena, B.'),
('Méndez, A.'),
('Péñaloza, R. E.'),
('Gigena, S.'),
('Gindikin, S.'),
('Harris, C.'),
('Adobe'),
('Antón, H.'),
('Dauben, J'),
('Escriba, C. J.'),
('George, B. T.'),
('Marsden, J.'), 
('Fonseca, Y. S.'),
('González, R. S.'),
('Araujo, A. D.'),
('Hernández, O. M.'),
('Ceballos, S. F.'),
('Horton, I.'),
('Fingermann, G.'),
('Osterwald, A'),
('Debnath, L.'),
('Zill, D.'),
('Giraldo, E.'),
('Sears, F.'),
('Motta, M.'),
('Pappas, J. L.'),
('Aho, A'),
('Savitch, W.'),
('Carrasco, V. L.'),
('Mora, W. F.'),
('Korth, H.'),
('MariaDB'),
('Markus, J.'),
('Roldan, A. J.'),
('Arya, J.'),
('Hinojosa, J.'),
('Kleiman, A.'),
('Lipchutz, S.'),
('Larson, H.'),
('Montgomery, D.'),
('Meredith, J.'),
('Project Management Institute'),
('Mano, M.'),
('Millman, J.'),
('Silberschatz, A.'),
('W3Schools'),
('IETF'),
('Rex, H.'),
('Puchol, L.'),
('Russell, S.'),
('Russell, M.');

INSERT INTO fuentes (tipo_id, titulo, editorial, anio, lugar, url) VALUES
(1, 'Algebra Superior', 'Editorial Trillas', 2014, 'México', NULL), 
(1, 'Imagine Math. Between Culture and Mathematics', 'Springer', 2012, 'Italia', NULL),
(1, 'Calculus with Applications', 'Springer', 2014, 'New York', NULL),
(1, 'Introduccion al Cálculo Vectorial', 'Thomson', 2003, 'México', NULL),
(1, 'Diseño de algoritmos y su programación en C', 'Alfaomega', 2013, 'México', NULL),
(1, 'Fundamentos de programación', 'UNAM ENEP Aragón', 2004, 'México', NULL),
(1, 'Álgebra y geometría: teoría, práctica y aplicaciones', 'Universitas Editorial Cientifica Universitaria', 2018, 'Argentina', NULL),
(1, 'Tales of Mathematicians and Physicists', 'Springer', 2007, 'New York', NULL),
(1, 'Engineering Ethics: Concepts and Cases', 'Wadsworth Publishing', 2014, 'USA', NULL),
(2, 'Documentación de Photoshop', NULL, 2017, NULL, 'https://helpx.adobe.com/support/photoshop.html'),
(1, 'Introducción al Álgebra Lineal', 'Limusa', 2003, 'México', NULL),
(1, 'Writing the History of Mathematics: Its Historical Development', 'Birkhäuser', 2002, 'Alemania', NULL),
(1, 'Cálculo varias variables', 'Pearson Education', 2015, 'México', NULL),
(1, 'Cálculo Vectorial', 'Pearson Education (Prentice Hall)', 2005, 'México', NULL),
(1, 'Comunicación oral y escrita', 'Pearson', 2016, 'México', NULL),
(1, 'Manual de redacción e investigación documental', 'Trillas', 2005, 'México', NULL),
(1, 'Presupuestos empresariales. Eje de la planeación financiera', 'Trillas', 2012, 'México', NULL),
(1, 'Administración de empresas', 'Piramide', 2014, 'España', NULL),
(1, 'Java 2 Curso de Programación', 'Alfaomega Ra-Ma', 2000, 'México', NULL),
(1, 'Beginning Java', 'John Wiley', 2011, 'USA', NULL),
(1, 'Relaciones humanas, fundamentos psicológicos y sociales', 'Editorial el ateneo', 1992, 'México', NULL),
(1, 'Generación de modelos de negocios', 'Wiley', 2010, 'New Jersey', NULL),
(1, 'Nonlinear partial differential equations', 'Birlchauser', 2013, 'USA', NULL),
(1, 'Ecuaciones diferenciales con aplicaciones de modelado', 'Thompson', 2006, 'México', NULL),
(1, 'Fundamentos de electricidad y magnetismo', 'Fondo Editorial EIA', 2015, 'Colombia', NULL),
(1, 'Física Universitaria', 'Addison-Wesley', 2008, 'México', NULL),
(1, 'Política de competencia: teoría y práctica', 'Fondo de Cultura Económica', 2018, 'Ciudad de México', NULL),
(1, 'Fundamentos de economía y administración', 'McGraw-Hill', 1993, 'México', NULL),
(1, 'Compiladores: principios, técnicas y herramientas', 'Addison Wesley', 2008, 'México', NULL),
(1, 'Absolute Java', 'Addison-Wesley', 2010, 'México', NULL),
(1, 'Métodos numéricos', 'Macro', 2011, 'Lima, Perú', NULL),
(1, 'Introducción a los Métodos Numéricos', 'Escuela de Matemáticas', 2016, 'Costa Rica', NULL),
(1, 'Fundamentos de Bases de Datos', 'McGraw-Hill', 2014, 'España', NULL),
(2, 'Manuales de MariaDB', NULL, 2017, NULL, NULL),
(1, 'Manual De Circuitos Electrónicos', 'Marcombo', 1987, 'México', NULL),
(1, 'Dispositivos electrónicos, problemas resueltos', 'Alfaomega', 2001, 'México', NULL),
(1, 'Matemáticas aplicadas a la administración y a la economía', 'Pearson', 2002, 'México', NULL),
(1, 'Evaluación económico-financiera de proyectos de inversión', 'Trillas', 2011, 'México', NULL),
(1, 'Aplicaciones matemáticas a la administración', 'Limusa', 1972, 'México', NULL),
(1, 'Teoría de conjuntos y temas afines', 'Mc Graw-Hill', 1973, 'Colombia', NULL),
(1, 'Introduction to probability theory and statistical inference', 'John Wiley & Sons', 1989, 'Canada', NULL),
(1, 'Applied statistics and probability for engineers', 'John Wiley & Sons', 2003, 'USA', NULL),
(1, 'Project Management: A managerial approach', 'John Wiley', 2003, 'USA', NULL),
(1, 'PMBOK Guide', 'Project Management Institute', 2017, NULL, NULL),
(1, 'Diseño Digital', 'Pearson Educación', 2013, 'México', NULL),
(1, 'Microelectronics', 'McGraw Hill', 2003, 'USA', NULL),
(1, 'Sistemas Operativos', 'Limusa', 2002, 'México', NULL),
(2, 'JavaScript Tutorial', NULL, 2017, NULL, 'https://www.w3schools.com/jS/default.asp'),
(2, 'RFC’s de la IEEE', NULL, 2015, NULL, 'https://tools.ietf.org/rfc/index'),
(1, 'A practical guide to database design', 'CRC Press', 2018, 'Boca Ratón', NULL),
(1, 'El libro de las habilidades directivas', 'Díaz de Santos', 2010, 'España', NULL),
(1, 'Inteligencia Artificial: Un enfoque moderno', 'Prentice Hall Hispanoamericano', 1996, 'México', NULL),
(1, 'Mining the social web', 'O’Reilly', 2011, 'USA', NULL);

INSERT INTO autor_fuente (autor_id, fuente_id) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5),
(6, 6),
(7, 7),
(8, 8),
(9, 9),
(10, 10),
(11, 11),
(12, 12),
(13, 12),
(14, 13),
(15, 14),
(16, 15),
(17, 16),
(18, 17),
(19, 18),
(20, 19),
(21, 20),
(22, 21),
(23, 22),
(24, 23),
(25, 24),
(26, 25),
(27, 26),
(28, 27),
(29, 28),
(30, 29),
(31, 30),
(32, 31),
(33, 32),
(34, 33),
(35, 34),
(36, 35),
(37, 36),
(38, 37),
(39, 38),
(40, 39),
(41, 40),
(42, 41),
(43, 42),
(44, 43),
(45, 44),
(46, 45),
(47, 46),
(48, 47),
(49, 48),
(50, 49),
(51, 50),
(52, 51),
(53, 52),
(54, 53);