INSERT INTO autores (nombre_completo) VALUES
("Cárdenas, T. H."),
("Emmer, M."),
("Lax, P."),
("Mena, B."),
("Méndez, A."),
("Péñaloza, R. E."),
("Gigena, S."),
("Gindikin, S."),
("Harris, C."),
("Adobe"),
("Antón, H."),
("Dauben, J"),
("Escriba, C. J."),
("George, B. T."),
("Marsden, J."), 
("Fonseca, Y. S."),
("González, R. S."),
("Araujo, A. D."),
("Hernández, O. M."),
("Ceballos, S. F."),
("Horton, I."),
("Fingermann, G."),
("Osterwald, A"),
("Debnath, L."),
("Zill, D."),
("Giraldo, E."),
("Sears, F."),
("Motta, M."),
("Pappas, J. L."),
("Aho, A"),
("Savitch, W."),
("Carrasco, V. L."),
("Mora, W. F."),
("Korth, H."),
("MariaDB"),
("Markus, J."),
("Roldan, A. J."),
("Arya, J."),
("Hinojosa, J."),
("Kleiman, A."),
("Lipchutz, S."),
("Larson, H."),
("Montgomery, D.");

INSERT INTO fuentes (tipo_id, titulo, editorial, anio, lugar, url) VALUES
(1, "Algebra Superior", "Editorial Trillas", 2014, "México"), 
(1, "Imagine Math. Between Culture and Mathematics", "Springer", 2012, "Italia"),
(1, "Calculus with Applications", "Springer", 2014, "New York"),
(1, "Introduccion al Cálculo Vectorial", "Thomson", 2003, "México"),
(1, "Diseño de algoritmos y su programación en C", "Alfaomega", 2013, "México"),
(1, "Fundamentos de programación", "UNAM ENEP Aragón", 2004, "México"),
(1, "Álgebra y geometría: teoría, práctica y aplicaciones", "Universitas Editorial Cientifica Universitaria", 2018, "Argentina"),
(1, "Tales of Mathematicians and Physicists", "Springer", 2007, "New York"),
(1, "Engineering Ethics: Concepts and Cases", "Wadsworth Publishing", 2014, "USA"),
(2, "Documentación de Photoshop", NULL,2017, NULL,"https://helpx.adobe.com/support/photoshop.html"),
(1, "Introducción al Álgebra Lineal", "Limusa", 2003, "México"),
(1, "Writing the History of Mathematics: Its Historical Development", "Birkhäuser", 2002, "Alemania"),
(1, "Cálculo varias variables", "Pearson Education", 2015, "México"),
(1, "Cálculo Vectorial", "Pearson Education (Prentice Hall)", 2005, "México"),
(1, "Comunicación oral y escrita", "Pearson", 2016, "México"),
(1, "Manual de redacción e investigación documental", "Trillas", 2005, "México"),
(1, "Presupuestos empresariales. Eje de la planeación financiera", "Trillas", 2012, "México"),
(1, "Administración de empresas", "Piramide", 2014, "España"),
(1, "Java 2 Curso de Programación", "Alfaomega Ra-Ma", 2000, "México"),
(1, "Beginning Java", "John Wiley", 2011, "USA"),
(1, "Relaciones humanas, fundamentos psicológicos y sociales", "Editorial el ateneo", 1992, "México"),
(1, "Generación de modelos de negocios", "Wiley", 2010, "New Jersey"),
(1, "Nonlinear partial differential equations", "Birlchauser", 2013, "USA"),
(1, "Ecuaciones diferenciales con aplicaciones de modelado", "Thompson", 2006, "México"),
(1, "Fundamentos de electricidad y magnetismo", "Fondo Editorial EIA", 2015, "Colombia"),
(1, "Física Universitaria", "Addison-Wesley", 2008, "México"),
(1, "Política de competencia: teoría y práctica", "Fondo de Cultura Económica", 2018, "Ciudad de México"),
(1, "Fundamentos de economía y administración", "McGraw-Hill", 1993, "México"),
(1, "Compiladores: principios, técnicas y herramientas", "Addison Wesley", 2008, "México"),
(1, "Absolute Java", "Addison-Wesley", 2010, "México"),
(1, "Métodos numéricos", "Macro", 2011, "Lima, Perú"),
(1, "Introducción a los Métodos Numéricos", "Escuela de Matemáticas", 2016, "Costa Rica"),
(1, "Fundamentos de Bases de Datos", "McGraw-Hill", 2014, "España"),
(2, "Manuales de MariaDB", NULL, 2017, NULL),
(1, "Manual De Circuitos Electrónicos", "Marcombo", 1987, "México"),
(1, "Dispositivos electrónicos, problemas resueltos", "Alfaomega", 2001, "México"),
(1, "Matemáticas aplicadas a la administración y a la economía", "Pearson", 2002, "México"),
(1, "Evaluación económico-financiera de proyectos de inversión", "Trillas", 2011, "México"),
(1, "Aplicaciones matemáticas a la administración", "Limusa", 1972, "México"),
(1, "Teoría de conjuntos y temas afines", "Mc Graw-Hill", 1973, "Colombia"),
(1, "Introduction to probability theory and statistical inference", "John Wiley & Sons", 1989, "Canada"),
(1, "Applied statistics and probability for engineers", "John Wiley & Sons", 2003, "USA");

INSERT INTO asignaturas (nombre, semestre) VALUES
('Álgebra', 1),
('Cálculo Diferencial e Integral', 1),
('Computadoras y Programación', 1),
('Geometría Analítica', 1),
('Introducción a la Ingeniería en Computación', 1),
('Álgebra Lineal', 2),
('Cálculo Vectorial', 2),
('Comunicación', 2),
('Emprendimiento 1', 2),
('Programación Orientada a Objetos', 2),
('Taller de creatividad e innovación', 2),
('Ecuaciones Diferenciales', 3),
('Electricidad y Magnetismo (L)', 3),
('Emprendimiento 2', 3),
('Estructura de Datos', 3),
('Métodos Numéricos', 3),
('Bases de Datos 1', 4),
('Dispositivos Electrónicos (L)', 4),
('Emprendimiento 3', 4),
('Matemáticas Discretas', 4),
('Probabilidad y Estadística', 4);
